public class LeadTriggerHandler extends TriggerHandler {
    
    List<Lead> newLeads;

    public LeadTriggerHandler(){
        
    }
    
    public override void beforeInsert() {
        				
    }
    public override void beforeUpdate() {
        				
    }
    public override void beforeDelete() {
        				
    }
    public override void afterInsert() {
        				
    }
    public override void afterUpdate() {
        				
    }
    public override void afterDelete() {
        				
    }
    public override void afterUndelete() {
        				
    }

}